/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.*;
import java.util.ArrayList;

/**
 * @author Diego Hiriart
 * @author Luis Corales
 * @author Martin Galvez
 * @author Daniel Alban
 * @author Daniela Estupinan
 */
public class Direcciones extends javax.swing.JInternalFrame {

    Admin recepcion = new Admin();
    
    /**
     * Creates new form Direcciones
     */
    public Direcciones(Admin recepcionP) {
        initComponents();
        this.recepcion = recepcionP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        partidaComboBox = new javax.swing.JComboBox<>();
        destinoComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccionesPane = new javax.swing.JEditorPane();
        calcularButton = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Direcciones para movilizarse en el hotel");

        jLabel1.setText("Punto de partida:");

        jLabel2.setText("Destino:");

        partidaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Entrada", "Camino pto. A", "Parqueadero", "Recepción", "Sala común", "Zona de parasoles", "Bar", "Piscina", "Duchas", "Camino pto. B", "Habs. 1-4 21-24", "Habs. 5-7 25 26", "Habs. 8-10 27 28", "Casa 11", "Casas 12-14" }));

        destinoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Entrada", "Camino pto. A", "Parqueadero", "Recepción", "Sala común", "Zona de parasoles", "Bar", "Piscina", "Duchas", "Camino pto. B", "Habs. 1-4 21-24", "Habs. 5-7 25 26", "Habs. 8-10 27 28", "Casa 11", "Casas 12-14" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ruta ideal:");

        jScrollPane1.setViewportView(direccionesPane);

        calcularButton.setText("Calcular");
        calcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(partidaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(destinoComboBox, 0, 294, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(calcularButton)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(partidaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(destinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calcularButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
        // TODO add your handling code here:
        if(this.partidaComboBox.getSelectedIndex()>0 && this.destinoComboBox.getSelectedIndex()>0){
            //Nodos
            Nodo entrada = new Nodo("Entrada"); Nodo caminoA = new Nodo("Camino pto. A"); Nodo parqueo = new Nodo("Parqueadero");
            Nodo recepcion = new Nodo("Recepción"); Nodo sala = new Nodo("Sala común"); Nodo parasoles = new Nodo("Zona de parasoles"); Nodo bar = new Nodo("Bar");
            Nodo piscina = new Nodo("Piscina"); Nodo duchas = new Nodo("Duchas"); Nodo caminoB = new Nodo("Camino pto. B"); 
            Nodo habs1 = new Nodo("Habs. 1-4, 21-24"); Nodo habs2 = new Nodo("Habs. 5-7, 25, 26"); Nodo habs3 = new Nodo("Habs. 8-10, 27, 28");
            Nodo casa11 =  new Nodo("Casa 11"); Nodo casas12 = new Nodo("Casas 12-14");
            //Aristas
            entrada.addArista(parqueo, 10); entrada.addArista(caminoA, 5.75); entrada.addArista(recepcion, 11.5);
            parqueo.addArista(entrada, 10); parqueo.addArista(caminoA, 8.44);
            caminoA.addArista(entrada, 5.75); caminoA.addArista(parqueo, 8.44); caminoA.addArista(recepcion, 9.7);
            caminoA.addArista(parasoles, 11.2); caminoA.addArista(piscina, 11.5); caminoA.addArista(caminoB, 23);
            recepcion.addArista(entrada, 11.5); recepcion.addArista(caminoA, 9.7); recepcion.addArista(sala, 7);
            sala.addArista(recepcion, 7);
            parasoles.addArista(caminoA, 11.2); parasoles.addArista(bar, 7); parasoles.addArista(piscina, 6); 
            parasoles.addArista(duchas, 8.8);
            piscina.addArista(caminoA, 15.5); piscina.addArista(parasoles, 6); piscina.addArista(bar, 8.5);
            piscina.addArista(duchas, 5.5); piscina.addArista(caminoB, 10.3);
            bar.addArista(parasoles, 7); bar.addArista(piscina, 8.5); bar.addArista(duchas, 6);
            duchas.addArista(bar, 6); duchas.addArista(parasoles, 8.8); duchas.addArista(piscina, 5.5);
            caminoB.addArista(caminoB, 23); caminoB.addArista(habs1, 5.2); caminoB.addArista(habs2, 9.38);
            caminoB.addArista(habs3, 7.2); caminoB.addArista(casa11, 10.42); caminoB.addArista(casas12, 5.49);
            caminoB.addArista(piscina, 10.3);
            habs1.addArista(caminoB, 5.2); habs2.addArista(caminoB, 9.38); habs3.addArista(caminoB, 7.2);
            casa11.addArista(caminoB, 10.42); casas12.addArista(caminoB, 5.49);
            
            ArrayList<Nodo> nodos = new ArrayList<Nodo>();
            nodos.add(entrada); nodos.add(caminoA); nodos.add(parqueo); nodos.add(recepcion);
            nodos.add(sala); nodos.add(parasoles); nodos.add(bar); nodos.add(piscina);
            nodos.add(duchas); nodos.add(caminoB); nodos.add(habs1); nodos.add(habs2);
            nodos.add(habs3); nodos.add(casa11); nodos.add(casas12);
            
            Grafo hotel = new Grafo(nodos);
            
            Nodo partida = nodos.get(this.partidaComboBox.getSelectedIndex()-1);
            
            hotel=hotel.dijkstra(hotel, partida);
            
            Nodo destino = hotel.getNodos().get(this.destinoComboBox.getSelectedIndex()-1);
            
            ArrayList<String> todos = hotel.camino(destino);
            String direcciones="Recorra en este orden: \n\n";
            for(int i=0; i<todos.size(); i++){
                direcciones+=todos.get(i)+"\n";              
            }     
            direcciones+=destino.getNombre()+"\n";
            
            this.direccionesPane.setText(direcciones);
        }
    }//GEN-LAST:event_calcularButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Direcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin recepcionP = new Admin();
                new Direcciones(recepcionP).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularButton;
    private javax.swing.JComboBox<String> destinoComboBox;
    private javax.swing.JEditorPane direccionesPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> partidaComboBox;
    // End of variables declaration//GEN-END:variables
}
