/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * @author Diego Hiriart
 * @author Luis Corales
 * @author Martin Galvez
 * @author Daniel Alban
 * @author Daniela Estupinan
 */
public class HistorialMantenimiento extends javax.swing.JInternalFrame {

    Admin recepcion = new Admin();
    
    /**
     * Creates new form HistorialMantenimiento
     */
    public HistorialMantenimiento(Admin recepcionP) {
        initComponents();
        this.recepcion = recepcionP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        habitacionComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        actualField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historialPane = new javax.swing.JTextPane();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Historial y estado de mantenimiento");

        jLabel1.setText("Habitación:");

        habitacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "27", "28" }));
        habitacionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado actual de mantenimiento:");

        actualField.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Historial");

        jScrollPane2.setViewportView(historialPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(habitacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(actualField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void habitacionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionComboBoxActionPerformed
        // TODO add your handling code here:
        //Actualiza el text field y editor pane
        if(this.habitacionComboBox.getSelectedIndex()>0){
            try{
                LocalDate ahora = LocalDate.now();//Da fecha actual 
                int habitacion = this.habitacionComboBox.getSelectedIndex();
                Fecha actual = new Fecha(ahora.getDayOfMonth(), ahora.getMonthValue(), ahora.getYear());
                File archivo = new File("PorteroAdminHotel\\Mantenimientos.txt");//C:\\PorteroAdminHotel\\Mantenimientos.txt  
                String historial="";
                try {
                    historial = Files.readAllLines(archivo.toPath()).get(this.habitacionComboBox.getSelectedIndex()-1);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error de lectura de archivo");
                }
                String[] mantNodos = historial.split(";");
                ListaMantenimiento mantenimiento = new ListaMantenimiento();
                this.actualField.setText("Actualmente libre");
                if(!historial.equalsIgnoreCase("")){
                    for(int i=0; i<mantNodos.length; i++){
                        String[] mantDatos = mantNodos[i].split(",");
                        String[] ini = mantDatos[1].split("-"), fi = mantDatos[2].split("-");
                        Fecha inicio = new Fecha(Integer.parseInt(ini[0]), Integer.parseInt(ini[1]), Integer.parseInt(ini[2])), 
                                fin = new Fecha(Integer.parseInt(fi[0]), Integer.parseInt(fi[1]), Integer.parseInt(fi[2])); 
                        Mantenimiento mant = new Mantenimiento(mantDatos[0], inicio, fin);
                        mantenimiento.insertar(mant);
                    }

                    NodoMantenimiento aux = mantenimiento.getInicio();
                    for(int i=0; i<mantNodos.length; i++){
                        Fecha inicio = aux.getDato().getInicio(), fin = aux.getDato().getFin();
                        if(mantenimiento.enMantenimiento(actual, inicio, fin)){
                           this.actualField.setText("Actualmente en mantenimiento"); 
                        }
                        aux=aux.getDerecha();
                    }
                }
                this.historialPane.setText(mantenimiento.imprimirConsulta());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error de lectura de archivo\n no existe la carpeta PorteroAdminHotel\\Finalizadas\\");
            }          
        }     
        
    }//GEN-LAST:event_habitacionComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin recepcionP = new Admin();
                new HistorialMantenimiento(recepcionP).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualField;
    private javax.swing.JComboBox<String> habitacionComboBox;
    private javax.swing.JTextPane historialPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
