/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.*;//Importa todas las clases se se utilizaran
import javax.swing.JDesktopPane;

/**
 * @author Diego Hiriart
 * @author Luis Corales
 * @author Martin Galvez
 * @author Daniel Alban
 * @author Daniela Estupinan
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Admin recepcionP = new Admin();
    JDesktopPane escritorio=new JDesktopPane();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalMenuBar = new javax.swing.JMenuBar();
        reservasMenu = new javax.swing.JMenu();
        registrarMenuItem = new javax.swing.JMenuItem();
        edicionFechasMenuItem = new javax.swing.JMenuItem();
        gastosMenuItem = new javax.swing.JMenuItem();
        cambioHabitacionMenuItem = new javax.swing.JMenuItem();
        finalizarMenuItem = new javax.swing.JMenuItem();
        serviciosInfoMenu = new javax.swing.JMenu();
        verEditarDisponibilidadMenuItem = new javax.swing.JMenuItem();
        consultarHabitacionMenuItem = new javax.swing.JMenuItem();
        mantenimientoHabitacionMenuItem = new javax.swing.JMenuItem();
        historialMantenimientoMenuItem = new javax.swing.JMenuItem();
        direccionesMenuItem = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        activasMenuItem = new javax.swing.JMenuItem();
        anterioresMenuItem = new javax.swing.JMenuItem();
        reporteFechasMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portero: Administrador digital hotelero");

        principalMenuBar.setName("Menu Principal"); // NOI18N

        reservasMenu.setText("Reservas");

        registrarMenuItem.setText("Registrar (check-in)");
        registrarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMenuItemActionPerformed(evt);
            }
        });
        reservasMenu.add(registrarMenuItem);

        edicionFechasMenuItem.setText("Editar fechas de inicio y fin");
        edicionFechasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicionFechasMenuItemActionPerformed(evt);
            }
        });
        reservasMenu.add(edicionFechasMenuItem);

        gastosMenuItem.setText("Añadir consumos y cobros");
        gastosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosMenuItemActionPerformed(evt);
            }
        });
        reservasMenu.add(gastosMenuItem);

        cambioHabitacionMenuItem.setText("Cambio de habitación");
        cambioHabitacionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioHabitacionMenuItemActionPerformed(evt);
            }
        });
        reservasMenu.add(cambioHabitacionMenuItem);

        finalizarMenuItem.setText("Finalizar (check-out)");
        finalizarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarMenuItemActionPerformed(evt);
            }
        });
        reservasMenu.add(finalizarMenuItem);

        principalMenuBar.add(reservasMenu);

        serviciosInfoMenu.setText("Servicios e información del hotel");

        verEditarDisponibilidadMenuItem.setText("Ver/editar disponibilidad de servicios");
        verEditarDisponibilidadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEditarDisponibilidadMenuItemActionPerformed(evt);
            }
        });
        serviciosInfoMenu.add(verEditarDisponibilidadMenuItem);

        consultarHabitacionMenuItem.setText("Consultar caracteristicas de habitación");
        consultarHabitacionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarHabitacionMenuItemActionPerformed(evt);
            }
        });
        serviciosInfoMenu.add(consultarHabitacionMenuItem);

        mantenimientoHabitacionMenuItem.setText("Registrar mantenimientos especiales de habitación");
        mantenimientoHabitacionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientoHabitacionMenuItemActionPerformed(evt);
            }
        });
        serviciosInfoMenu.add(mantenimientoHabitacionMenuItem);

        historialMantenimientoMenuItem.setText("Ver estado e historial de mantenimientos especiales");
        historialMantenimientoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialMantenimientoMenuItemActionPerformed(evt);
            }
        });
        serviciosInfoMenu.add(historialMantenimientoMenuItem);

        direccionesMenuItem.setText("Direcciones para movilizarse en el hotel");
        direccionesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionesMenuItemActionPerformed(evt);
            }
        });
        serviciosInfoMenu.add(direccionesMenuItem);

        principalMenuBar.add(serviciosInfoMenu);

        reportesMenu.setText("Reportes");

        activasMenuItem.setText("Ver reservas activas");
        activasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activasMenuItemActionPerformed(evt);
            }
        });
        reportesMenu.add(activasMenuItem);

        anterioresMenuItem.setText("Ver reservas anteriores");
        anterioresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterioresMenuItemActionPerformed(evt);
            }
        });
        reportesMenu.add(anterioresMenuItem);

        reporteFechasMenuItem.setText("Reportes por rango de fecha");
        reporteFechasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteFechasMenuItemActionPerformed(evt);
            }
        });
        reportesMenu.add(reporteFechasMenuItem);

        principalMenuBar.add(reportesMenu);

        setJMenuBar(principalMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMenuItemActionPerformed
        // TODO add your handling code here:
        NuevaReserva nuevo=new NuevaReserva(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_registrarMenuItemActionPerformed

    private void edicionFechasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicionFechasMenuItemActionPerformed
        // TODO add your handling code here:
        EdicionFechas nuevo = new EdicionFechas(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_edicionFechasMenuItemActionPerformed

    private void gastosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosMenuItemActionPerformed
        // TODO add your handling code here:
        Consumos nuevo = new Consumos(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);

    }//GEN-LAST:event_gastosMenuItemActionPerformed

    private void cambioHabitacionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioHabitacionMenuItemActionPerformed
        // TODO add your handling code here:
        CambioHabitacion nuevo = new CambioHabitacion(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_cambioHabitacionMenuItemActionPerformed

    private void finalizarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarMenuItemActionPerformed
        // TODO add your handling code here:
        Finalizacion nuevo = new Finalizacion(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_finalizarMenuItemActionPerformed

    private void verEditarDisponibilidadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEditarDisponibilidadMenuItemActionPerformed
        // TODO add your handling code here:
        Servicios nuevo = new Servicios(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_verEditarDisponibilidadMenuItemActionPerformed

    private void consultarHabitacionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarHabitacionMenuItemActionPerformed
        // TODO add your handling code here:
        ConsultaHabitacion nuevo = new ConsultaHabitacion(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_consultarHabitacionMenuItemActionPerformed

    private void mantenimientoHabitacionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientoHabitacionMenuItemActionPerformed
        // TODO add your handling code here:
        MantenimientoEspecial nuevo = new MantenimientoEspecial(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_mantenimientoHabitacionMenuItemActionPerformed

    private void historialMantenimientoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialMantenimientoMenuItemActionPerformed
        // TODO add your handling code here:
        HistorialMantenimiento nuevo = new HistorialMantenimiento(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_historialMantenimientoMenuItemActionPerformed

    private void direccionesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionesMenuItemActionPerformed
        // TODO add your handling code here:
        Direcciones nuevo = new Direcciones(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_direccionesMenuItemActionPerformed

    private void activasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activasMenuItemActionPerformed
        // TODO add your handling code here:
        Activas nuevo = new Activas(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_activasMenuItemActionPerformed

    private void anterioresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterioresMenuItemActionPerformed
        // TODO add your handling code here:
        Anteriores nuevo = new Anteriores(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_anterioresMenuItemActionPerformed

    private void reporteFechasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteFechasMenuItemActionPerformed
        // TODO add your handling code here:
        ReporteFechas nuevo = new ReporteFechas(recepcionP);
        nuevo.setVisible(true);
        nuevo.pack();
        escritorio.add(nuevo);
        setContentPane(escritorio);
    }//GEN-LAST:event_reporteFechasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem activasMenuItem;
    private javax.swing.JMenuItem anterioresMenuItem;
    private javax.swing.JMenuItem cambioHabitacionMenuItem;
    private javax.swing.JMenuItem consultarHabitacionMenuItem;
    private javax.swing.JMenuItem direccionesMenuItem;
    private javax.swing.JMenuItem edicionFechasMenuItem;
    private javax.swing.JMenuItem finalizarMenuItem;
    private javax.swing.JMenuItem gastosMenuItem;
    private javax.swing.JMenuItem historialMantenimientoMenuItem;
    private javax.swing.JMenuItem mantenimientoHabitacionMenuItem;
    private javax.swing.JMenuBar principalMenuBar;
    private javax.swing.JMenuItem registrarMenuItem;
    private javax.swing.JMenuItem reporteFechasMenuItem;
    private javax.swing.JMenu reportesMenu;
    private javax.swing.JMenu reservasMenu;
    private javax.swing.JMenu serviciosInfoMenu;
    private javax.swing.JMenuItem verEditarDisponibilidadMenuItem;
    // End of variables declaration//GEN-END:variables
}
